id: TASK-006
title: Guard Policy Overrides & Report v2
feature: guard-automation
decision: ADR-0002
owner: @ai-agent
status: review
story_points: 3
depends_on: [TASK-003]
prio: P0
due: 2025-10-24
acceptance:
  - Guard reads override trailers from overlay commits, publish tags, and `refs/notes/forked/override` in documented precedence order (commit → tag → note) while respecting `policy_overrides` config.
  - `guards.mode=require-override` fails without valid override and passes with allowed override values; disallowed scopes fail with clear messaging.
  - `.forked/report.json` increments to `report_version: 2` and includes `override` and `features` blocks (populated from provenance or resolver fallback).
  - Tests cover commit/tag/note overrides, precedence (first match wins), allowed/disallowed scope combinations, and provenance fallback messaging.
links:
  - ../../../../adr/0002-guard-cli-contract.md
  - ../../../../../Forked CLI Expansion Implementation Plan.md
  - ../../../../features/guard-automation/implementation/plan.md
